/* ============================================================
   TMS-Twin :: Embedded Site Master Database (SMDB) extract
   Source: Partial_SMDB_for_Power_Apps_and_AI.xlsx
   This file embeds the dataset directly so the MVP runs from
   a plain static file with zero backend / zero build step.
   ============================================================ */

window.SMDB_SITES = [
 {
  "siteCode": "AHM8024",
  "siteName": "AHM8024__H_Chak184-9L ",
  "lat": 30.5394,
  "lon": 72.9028,
  "region": "Central A",
  "zone": 25,
  "city": "Ahmedabad",
  "tehsil": "CHICHAWATNI ",
  "district": "SAHIWAL",
  "province": "PUNJAB",
  "onAirDate": "2008-02-12",
  "opStatus": "On Air",
  "structureType": "Self-Supported Tower",
  "towerHeight": 46,
  "siteType": "GBT",
  "siteCategory": "Normal",
  "commercialCategory": "Platinum",
  "indoorOutdoor": "Outdoor",
  "macroTxn": "MACRO",
  "vendor": "Huawei",
  "currentTech": "2G+4G",
  "total2G": 3,
  "total4G": 9,
  "mbu": "C3-SWL-01",
  "mbuLead": "Syed Shahzad Hussain Kazmi",
  "mbuLeadEmail": "shahzad.kazmi@jazz.com.pk",
  "mbuLeadContact": "0303-9242311",
  "zonalManager": "Usman  Khalid",
  "zonalManagerEmail": "usman.khalid@engro.com",
  "zonalManagerContact": "0302-8480264",
  "roh": "Waqas  Naeem",
  "rohEmail": "waqas.naeem@engro.com",
  "rohContact": "0300-8711033",
  "address": "Chak # 184/9-L, Tehsil Cheecha Watni, Distt Sahiwal",
  "dateOfConstruction": "2008-02-12",
  "leaseExpiry": "2028-01-17",
  "annualRent": 249471.3795,
  "landlordType": "INDIVIDUAL",
  "dualBandAntennas": 3,
  "tribandAntennas": 3,
  "antenna4T6S": 0,
  "mmAntenna": 0,
  "massiveMimoAAU": 0,
  "totalRFAntenna": 6,
  "totalRRUs": 12,
  "totalMWAntenna": 1,
  "fiber": "No",
  "noOfBSDDishes": 0,
  "sizeOfDishes": 0,
  "designCapacity": 12.66,
  "capacityUsedJazz": 4.629003000000001,
  "capacityUsedOthers": "0",
  "totalCapacityUsed": 4.629003000000001,
  "availableCapacity": 8.030997,
  "availableCapacityPct": 0.634359952606635,
  "towerLoadingStatus": "Not Overloaded",
  "solarized": "Yes",
  "solarDeployDate": "2025-11-28",
  "solarLoadDesign": "No",
  "onGrid": null,
  "gridType": "Good Grid",
  "transformerEntity": "Deodar",
  "transformerCapacityKVA": "25 KVA",
  "numRectifiers": 1,
  "rectifier1Manufacturer": "Huawei ETP48400",
  "rectifier1CapacityKW": null,
  "rectifier1Modules": 0,
  "rectifier2Manufacturer": null,
  "batteryBank1Type": "Obsolete",
  "batteryBank1Cells": 3,
  "batteryBank1AH": null,
  "batteryBank1Install": "Greater than 5 years",
  "dg1ModelMake": null,
  "dg1RatingKVA": "9",
  "dg1Status": "Operational",
  "dg1InstallDate": "Greater than 10 years",
  "rms": "No",
  "rmsVendor": "No",
  "flmVendor": "HNL",
  "totalTenants": 1,
  "anchorTenantJazz": 1,
  "thirdPartyTenants": null,
  "guestOMO1": null,
  "guestOMO2": null,
  "guestOMO3": null,
  "hardAccessArea": null,
  "clusterId": 0,
  "isHub": false
 },
 {
  "siteCode": "AHM8025",
  "siteName": "AHM8025__H_Chak139-9L",
  "lat": 30.5224,
  "lon": 72.9711,
  "region": "Central A",
  "zone": 25,
  "city": "Ahmedabad",
  "tehsil": "SAHIWAL ",
  "district": "SAHIWAL",
  "province": "PUNJAB",
  "onAirDate": "2008-02-12",
  "opStatus": "On Air",
  "structureType": "Self-Supported Tower",
  "towerHeight": 46,
  "siteType": "GBT",
  "siteCategory": "Normal",
  "commercialCategory": "Platinum",
  "indoorOutdoor": "Outdoor",
  "macroTxn": "MACRO",
  "vendor": "Huawei",
  "currentTech": "2G+4G",
  "total2G": 3,
  "total4G": 9,
  "mbu": "C3-SWL-01",
  "mbuLead": "Syed Shahzad Hussain Kazmi",
  "mbuLeadEmail": "shahzad.kazmi@jazz.com.pk",
  "mbuLeadContact": "0303-9242311",
  "zonalManager": "Usman  Khalid",
  "zonalManagerEmail": "usman.khalid@engro.com",
  "zonalManagerContact": "0302-8480264",
  "roh": "Waqas  Naeem",
  "rohEmail": "waqas.naeem@engro.com",
  "rohContact": "0300-8711033",
  "address": "Plot of land bearing khata no 93/83, Khatooni no 302, situated at Chak # 139/9-L, Tehsil & Distt Sahiwal",
  "dateOfConstruction": "2008-02-12",
  "leaseExpiry": "2028-01-17",
  "annualRent": 356678.511,
  "landlordType": "INDIVIDUAL",
  "dualBandAntennas": 3,
  "tribandAntennas": 3,
  "antenna4T6S": 0,
  "mmAntenna": 0,
  "massiveMimoAAU": 0,
  "totalRFAntenna": 6,
  "totalRRUs": 12,
  "totalMWAntenna": 6,
  "fiber": "No",
  "noOfBSDDishes": 0,
  "sizeOfDishes": 0,
  "designCapacity": 12.66,
  "capacityUsedJazz": 8.585403,
  "capacityUsedOthers": 7.939143,
  "totalCapacityUsed": 16.524546,
  "availableCapacity": -3.8645460000000007,
  "availableCapacityPct": -0.30525639810426547,
  "towerLoadingStatus": "Slightly Overloaded",
  "solarized": "No",
  "solarDeployDate": null,
  "solarLoadDesign": "No",
  "onGrid": null,
  "gridType": "Good Grid",
  "transformerEntity": "Deodar",
  "transformerCapacityKVA": "25 KVA",
  "numRectifiers": 1,
  "rectifier1Manufacturer": "Vertiv",
  "rectifier1CapacityKW": null,
  "rectifier1Modules": null,
  "rectifier2Manufacturer": null,
  "batteryBank1Type": "Obsolete",
  "batteryBank1Cells": 3,
  "batteryBank1AH": null,
  "batteryBank1Install": "Greater than 5 years",
  "dg1ModelMake": null,
  "dg1RatingKVA": "9",
  "dg1Status": "Operational",
  "dg1InstallDate": "Greater than 10 years",
  "rms": "No",
  "rmsVendor": "No",
  "flmVendor": "HNL",
  "totalTenants": 3,
  "anchorTenantJazz": 1,
  "thirdPartyTenants": 2,
  "guestOMO1": "Telenor",
  "guestOMO2": "CM-PAK",
  "guestOMO3": null,
  "hardAccessArea": null,
  "clusterId": 0,
  "isHub": true
 },
 {
  "siteCode": "AKA7571",
  "siteName": "AKA7571__P_Chak89",
  "lat": 29.5561,
  "lon": 73.1853,
  "region": "Central A",
  "zone": 28,
  "city": "Akhtarabad",
  "tehsil": "BAHAWALNAGAR ",
  "district": "BAHAWALNAGAR",
  "province": "PUNJAB",
  "onAirDate": "2007-12-12",
  "opStatus": "On Air",
  "structureType": "Self-Supported Tower",
  "towerHeight": 46,
  "siteType": "GBT",
  "siteCategory": "Normal",
  "commercialCategory": "General",
  "indoorOutdoor": "Outdoor",
  "macroTxn": "MACRO",
  "vendor": "ZTE",
  "currentTech": "2G+4G",
  "total2G": 3,
  "total4G": 9,
  "mbu": "C3-BWN-04",
  "mbuLead": "Abid  Muneer",
  "mbuLeadEmail": "abid.muneer@engro.com",
  "mbuLeadContact": "0300-6936599",
  "zonalManager": "Usman  Khalid",
  "zonalManagerEmail": "usman.khalid@engro.com",
  "zonalManagerContact": "0302-8480264",
  "roh": "Waqas  Naeem",
  "rohEmail": "waqas.naeem@engro.com",
  "rohContact": "0300-8711033",
  "address": "Plot of land measuring 10M bearing Ahata #12,Situated at chak #89-5R,Tehsil Haroonabad Distt Bahawalnagar",
  "dateOfConstruction": "2007-12-12",
  "leaseExpiry": "2027-11-09",
  "annualRent": 251550.15899999999,
  "landlordType": "INDIVIDUAL",
  "dualBandAntennas": 3,
  "tribandAntennas": 3,
  "antenna4T6S": 0,
  "mmAntenna": 0,
  "massiveMimoAAU": 0,
  "totalRFAntenna": 6,
  "totalRRUs": 8,
  "totalMWAntenna": 1,
  "fiber": "No",
  "noOfBSDDishes": 0,
  "sizeOfDishes": 0,
  "designCapacity": 12.66,
  "capacityUsedJazz": 5.123553,
  "capacityUsedOthers": "0",
  "totalCapacityUsed": 5.123553,
  "availableCapacity": 7.536447,
  "availableCapacityPct": 0.5952959715639811,
  "towerLoadingStatus": "Not Overloaded",
  "solarized": "No",
  "solarDeployDate": null,
  "solarLoadDesign": "No",
  "onGrid": null,
  "gridType": "Good Grid",
  "transformerEntity": "Deodar",
  "transformerCapacityKVA": "25 KVA",
  "numRectifiers": 1,
  "rectifier1Manufacturer": "Emerson",
  "rectifier1CapacityKW": null,
  "rectifier1Modules": null,
  "rectifier2Manufacturer": null,
  "batteryBank1Type": "Obsolete",
  "batteryBank1Cells": 3,
  "batteryBank1AH": null,
  "batteryBank1Install": "Greater than 5 years",
  "dg1ModelMake": null,
  "dg1RatingKVA": null,
  "dg1Status": null,
  "dg1InstallDate": null,
  "rms": "No",
  "rmsVendor": "No",
  "flmVendor": "HNL",
  "totalTenants": 1,
  "anchorTenantJazz": 1,
  "thirdPartyTenants": null,
  "guestOMO1": null,
  "guestOMO2": null,
  "guestOMO3": null,
  "hardAccessArea": null,
  "clusterId": 1,
  "isHub": false
 },
 {
  "siteCode": "AKA7572",
  "siteName": "AKA7572__S_Chak92-6R",
  "lat": 29.5155,
  "lon": 73.1702,
  "region": "Central A",
  "zone": 28,
  "city": "Akhtarabad",
  "tehsil": "HAROONABAD ",
  "district": "BAHAWALNAGAR",
  "province": "PUNJAB",
  "onAirDate": "2007-12-12",
  "opStatus": "On Air",
  "structureType": "Self-Supported Tower",
  "towerHeight": 46,
  "siteType": "GBT",
  "siteCategory": "Normal",
  "commercialCategory": "Platinum",
  "indoorOutdoor": "Outdoor",
  "macroTxn": "MACRO",
  "vendor": "ZTE",
  "currentTech": "2G+4G",
  "total2G": 3,
  "total4G": 9,
  "mbu": "C3-BWN-04",
  "mbuLead": "Abid  Muneer",
  "mbuLeadEmail": "abid.muneer@engro.com",
  "mbuLeadContact": "0300-6936599",
  "zonalManager": "Usman  Khalid",
  "zonalManagerEmail": "usman.khalid@engro.com",
  "zonalManagerContact": "0302-8480264",
  "roh": "Waqas  Naeem",
  "rohEmail": "waqas.naeem@engro.com",
  "rohContact": "0300-8711033",
  "address": "Plot of land 11 M,bearing khewait #30,khatooni 30,situated at chak 92/6R,Tehsil Haroonabad Distt Bahawalnagar",
  "dateOfConstruction": "2007-12-12",
  "leaseExpiry": "2027-11-09",
  "annualRent": 269403.5925,
  "landlordType": "INDIVIDUAL",
  "dualBandAntennas": 3,
  "tribandAntennas": 3,
  "antenna4T6S": 0,
  "mmAntenna": 0,
  "massiveMimoAAU": 0,
  "totalRFAntenna": 6,
  "totalRRUs": 11,
  "totalMWAntenna": 3,
  "fiber": "No",
  "noOfBSDDishes": 0,
  "sizeOfDishes": 0,
  "designCapacity": 12.66,
  "capacityUsedJazz": 8.302803,
  "capacityUsedOthers": 3.4254,
  "totalCapacityUsed": 11.728203,
  "availableCapacity": 0.9317969999999995,
  "availableCapacityPct": 0.07360165876777247,
  "towerLoadingStatus": "Not Overloaded",
  "solarized": "No",
  "solarDeployDate": null,
  "solarLoadDesign": "No",
  "onGrid": null,
  "gridType": "Good Grid",
  "transformerEntity": "Deodar",
  "transformerCapacityKVA": "25 KVA",
  "numRectifiers": 1,
  "rectifier1Manufacturer": "Emerson",
  "rectifier1CapacityKW": null,
  "rectifier1Modules": null,
  "rectifier2Manufacturer": null,
  "batteryBank1Type": "Huawei Li-ion (100 AH)",
  "batteryBank1Cells": 4,
  "batteryBank1AH": null,
  "batteryBank1Install": "2023-12-27",
  "dg1ModelMake": null,
  "dg1RatingKVA": "20",
  "dg1Status": "Operational",
  "dg1InstallDate": "Greater than 10 years",
  "rms": "No",
  "rmsVendor": "No",
  "flmVendor": "HNL",
  "totalTenants": 2,
  "anchorTenantJazz": 1,
  "thirdPartyTenants": 1,
  "guestOMO1": "CM-PAK",
  "guestOMO2": null,
  "guestOMO3": null,
  "hardAccessArea": null,
  "clusterId": 1,
  "isHub": true
 },
 {
  "siteCode": "AKD2954",
  "siteName": "AKD2954__S_Amrakhurd",
  "lat": 32.6681,
  "lon": 73.6582,
  "region": "Central A",
  "zone": 10,
  "city": "Amra Khurd",
  "tehsil": "MANDI BAHAUDDIN ",
  "district": "MANDI BAHAUDDIN",
  "province": "PUNJAB",
  "onAirDate": "2008-04-04",
  "opStatus": "On Air",
  "structureType": "Self-Supported Tower",
  "towerHeight": 46,
  "siteType": "GBT",
  "siteCategory": "Normal",
  "commercialCategory": "General",
  "indoorOutdoor": "Outdoor",
  "macroTxn": "MACRO",
  "vendor": "Huawei",
  "currentTech": "2G+4G",
  "total2G": 3,
  "total4G": 6,
  "mbu": "C4-MBD-08",
  "mbuLead": "Waqas  Ahmed",
  "mbuLeadEmail": "w.ahmed@engro.com",
  "mbuLeadContact": "0302-8463897",
  "zonalManager": "Ovais Ali Khan",
  "zonalManagerEmail": "ovais.ali@engro.com",
  "zonalManagerContact": "0306-4000683",
  "roh": "Waqas  Naeem",
  "rohEmail": "waqas.naeem@engro.com",
  "rohContact": "0300-8711033",
  "address": "Open plot of land measuring 10 Marlas Bearing Khewat no. 83, Khatooni No. 324, Khasra no.794 situated at Village Amra khurd, PO Amra Khurd, Tehsil Kharian, Distt Gujrat.",
  "dateOfConstruction": "2008-04-04",
  "leaseExpiry": "2028-02-25",
  "annualRent": 264023.8755,
  "landlordType": "INDIVIDUAL",
  "dualBandAntennas": 3,
  "tribandAntennas": 3,
  "antenna4T6S": 0,
  "mmAntenna": 0,
  "massiveMimoAAU": 0,
  "totalRFAntenna": 6,
  "totalRRUs": 9,
  "totalMWAntenna": 1,
  "fiber": "No",
  "noOfBSDDishes": 0,
  "sizeOfDishes": 0,
  "designCapacity": 12.66,
  "capacityUsedJazz": 4.275753,
  "capacityUsedOthers": "0",
  "totalCapacityUsed": 4.275753,
  "availableCapacity": 8.384247,
  "availableCapacityPct": 0.6622627962085308,
  "towerLoadingStatus": "Not Overloaded",
  "solarized": "No",
  "solarDeployDate": null,
  "solarLoadDesign": "No",
  "onGrid": null,
  "gridType": "Good Grid",
  "transformerEntity": "Deodar",
  "transformerCapacityKVA": "25 KVA",
  "numRectifiers": 1,
  "rectifier1Manufacturer": "Huawei ETP48400",
  "rectifier1CapacityKW": null,
  "rectifier1Modules": 0,
  "rectifier2Manufacturer": null,
  "batteryBank1Type": "Huawei Li-ion (100 AH)",
  "batteryBank1Cells": 6,
  "batteryBank1AH": null,
  "batteryBank1Install": "2022-05-31",
  "dg1ModelMake": null,
  "dg1RatingKVA": "20",
  "dg1Status": "Operational",
  "dg1InstallDate": "Greater than 10 years",
  "rms": "Yes",
  "rmsVendor": "Huawei RMS Connected",
  "flmVendor": "Huawei",
  "totalTenants": 1,
  "anchorTenantJazz": 1,
  "thirdPartyTenants": null,
  "guestOMO1": null,
  "guestOMO2": null,
  "guestOMO3": null,
  "hardAccessArea": null,
  "clusterId": 2,
  "isHub": true
 },
 {
  "siteCode": "ALC3049",
  "siteName": "ALC3049__S_JamiaMuhammadia",
  "lat": 32.2708,
  "lon": 73.8122,
  "region": "Central A",
  "zone": 9,
  "city": "Alipur Chatha",
  "tehsil": "WAZIRABAD ",
  "district": "GUJRANWALA",
  "province": "PUNJAB",
  "onAirDate": "2008-02-29",
  "opStatus": "On Air",
  "structureType": "Self-Supported Tower",
  "towerHeight": 46,
  "siteType": "GBT",
  "siteCategory": "Normal",
  "commercialCategory": "Platinum",
  "indoorOutdoor": "Outdoor",
  "macroTxn": "MACRO",
  "vendor": "Huawei",
  "currentTech": "2G+4G",
  "total2G": 3,
  "total4G": 12,
  "mbu": "C4-HFZ-06",
  "mbuLead": "Syed Mansoor Hyder Shah",
  "mbuLeadEmail": "mansoor.hyder@engro.com",
  "mbuLeadContact": "0300-8673770",
  "zonalManager": "Ovais Ali Khan",
  "zonalManagerEmail": "ovais.ali@engro.com",
  "zonalManagerContact": "0306-4000683",
  "roh": "Waqas  Naeem",
  "rohEmail": "waqas.naeem@engro.com",
  "rohContact": "0300-8711033",
  "address": "Khewat No356,Khetoni 629,Khasra No561,563 Jamia Muhammadia,Rasool Nagar Road,Alipur Chatha,District Gujranwala",
  "dateOfConstruction": "2008-02-29",
  "leaseExpiry": "2028-02-04",
  "annualRent": 287877.45,
  "landlordType": "COMPANY",
  "dualBandAntennas": 3,
  "tribandAntennas": 3,
  "antenna4T6S": 3,
  "mmAntenna": 0,
  "massiveMimoAAU": 0,
  "totalRFAntenna": 9,
  "totalRRUs": 18,
  "totalMWAntenna": 1,
  "fiber": "No",
  "noOfBSDDishes": 0,
  "sizeOfDishes": 0,
  "designCapacity": 12.66,
  "capacityUsedJazz": 7.283226000000001,
  "capacityUsedOthers": 2.36565,
  "totalCapacityUsed": 9.648876000000001,
  "availableCapacity": 3.011123999999999,
  "availableCapacityPct": 0.23784549763033166,
  "towerLoadingStatus": "Not Overloaded",
  "solarized": "No",
  "solarDeployDate": null,
  "solarLoadDesign": "No",
  "onGrid": null,
  "gridType": "Good Grid",
  "transformerEntity": "Deodar",
  "transformerCapacityKVA": "25 KVA",
  "numRectifiers": 1,
  "rectifier1Manufacturer": "Huawei",
  "rectifier1CapacityKW": null,
  "rectifier1Modules": 24,
  "rectifier2Manufacturer": null,
  "batteryBank1Type": "Huawei Li-ion (100 AH)",
  "batteryBank1Cells": 4,
  "batteryBank1AH": null,
  "batteryBank1Install": "2023-09-05",
  "dg1ModelMake": null,
  "dg1RatingKVA": null,
  "dg1Status": null,
  "dg1InstallDate": null,
  "rms": "No",
  "rmsVendor": "No",
  "flmVendor": "Huawei",
  "totalTenants": 2,
  "anchorTenantJazz": 1,
  "thirdPartyTenants": 1,
  "guestOMO1": "CM-PAK",
  "guestOMO2": null,
  "guestOMO3": null,
  "hardAccessArea": null,
  "clusterId": 3,
  "isHub": false
 },
 {
  "siteCode": "ALC3447",
  "siteName": "ALC3447__H_IkalGarhAlipurChat",
  "lat": 32.266055,
  "lon": 73.816358,
  "region": "Central A",
  "zone": 9,
  "city": "Alipur Chatha",
  "tehsil": "WAZIRABAD ",
  "district": "GUJRANWALA",
  "province": "PUNJAB",
  "onAirDate": "2004-07-23",
  "opStatus": "On Air",
  "structureType": "Self-Supported Tower",
  "towerHeight": 46,
  "siteType": "GBT",
  "siteCategory": "Normal",
  "commercialCategory": "Hub",
  "indoorOutdoor": "Outdoor",
  "macroTxn": "MACRO",
  "vendor": "Huawei",
  "currentTech": "2G+4G",
  "total2G": 4,
  "total4G": 20,
  "mbu": "C4-HFZ-06",
  "mbuLead": "Syed Mansoor Hyder Shah",
  "mbuLeadEmail": "mansoor.hyder@engro.com",
  "mbuLeadContact": "0300-8673770",
  "zonalManager": "Ovais Ali Khan",
  "zonalManagerEmail": "ovais.ali@engro.com",
  "zonalManagerContact": "0306-4000683",
  "roh": "Waqas  Naeem",
  "rohEmail": "waqas.naeem@engro.com",
  "rohContact": "0300-8711033",
  "address": "Moza Ikal Garh Alipur Chatha Tehsil Wazirabad \nDist Gujrawalla ",
  "dateOfConstruction": "2004-07-23",
  "leaseExpiry": "2027-04-29",
  "annualRent": 513102.3975,
  "landlordType": "INDIVIDUAL",
  "dualBandAntennas": 4,
  "tribandAntennas": 0,
  "antenna4T6S": 0,
  "mmAntenna": 3,
  "massiveMimoAAU": 0,
  "totalRFAntenna": 7,
  "totalRRUs": 12,
  "totalMWAntenna": 17,
  "fiber": "Yes",
  "noOfBSDDishes": 1,
  "sizeOfDishes": 0.6,
  "designCapacity": 15.569999999999999,
  "capacityUsedJazz": 20.370482,
  "capacityUsedOthers": "0",
  "totalCapacityUsed": 20.370482,
  "availableCapacity": -4.800482000000001,
  "availableCapacityPct": -0.30831612074502257,
  "towerLoadingStatus": "Slightly Overloaded",
  "solarized": "No",
  "solarDeployDate": null,
  "solarLoadDesign": "No",
  "onGrid": null,
  "gridType": "Poor Grid",
  "transformerEntity": "Deodar",
  "transformerCapacityKVA": "25 KVA",
  "numRectifiers": 1,
  "rectifier1Manufacturer": "Vertiv",
  "rectifier1CapacityKW": null,
  "rectifier1Modules": null,
  "rectifier2Manufacturer": null,
  "batteryBank1Type": "Narada Li-ion",
  "batteryBank1Cells": 4,
  "batteryBank1AH": null,
  "batteryBank1Install": "2020-07-18",
  "dg1ModelMake": null,
  "dg1RatingKVA": "30",
  "dg1Status": "Operational",
  "dg1InstallDate": "Greater than 10 years",
  "rms": "No",
  "rmsVendor": "No",
  "flmVendor": "Huawei",
  "totalTenants": 1,
  "anchorTenantJazz": 1,
  "thirdPartyTenants": null,
  "guestOMO1": null,
  "guestOMO2": null,
  "guestOMO3": null,
  "hardAccessArea": null,
  "clusterId": 3,
  "isHub": true
 },
 {
  "siteCode": "ALC8810",
  "siteName": "ALC8810__P_ChoriGali",
  "lat": 32.2667,
  "lon": 73.8142,
  "region": "Central A",
  "zone": 9,
  "city": "Alipur Chatha",
  "tehsil": "WAZIRABAD ",
  "district": "GUJRANWALA",
  "province": "PUNJAB",
  "onAirDate": "2005-09-29",
  "opStatus": "On Air",
  "structureType": "Tubular",
  "towerHeight": 25,
  "siteType": "GBT",
  "siteCategory": "Normal",
  "commercialCategory": "Platinum",
  "indoorOutdoor": "Outdoor",
  "macroTxn": "MACRO",
  "vendor": "Huawei",
  "currentTech": "2G+4G",
  "total2G": 3,
  "total4G": 18,
  "mbu": "C4-HFZ-06",
  "mbuLead": "Syed Mansoor Hyder Shah",
  "mbuLeadEmail": "mansoor.hyder@engro.com",
  "mbuLeadContact": "0300-8673770",
  "zonalManager": "Ovais Ali Khan",
  "zonalManagerEmail": "ovais.ali@engro.com",
  "zonalManagerContact": "0306-4000683",
  "roh": "Waqas  Naeem",
  "rohEmail": "waqas.naeem@engro.com",
  "rohContact": "0300-8711033",
  "address": "Open Space aat Plot H-752 Muhallah Chori Galli Paki Dewarhi Ali pur Chatha ",
  "dateOfConstruction": "2005-09-29",
  "leaseExpiry": "2025-08-11",
  "annualRent": 542964.8805,
  "landlordType": "INDIVIDUAL",
  "dualBandAntennas": 3,
  "tribandAntennas": 0,
  "antenna4T6S": 0,
  "mmAntenna": 3,
  "massiveMimoAAU": 0,
  "totalRFAntenna": 6,
  "totalRRUs": 9,
  "totalMWAntenna": 2,
  "fiber": "No",
  "noOfBSDDishes": 1,
  "sizeOfDishes": 0.6,
  "designCapacity": 7.5,
  "capacityUsedJazz": 4.428248999999999,
  "capacityUsedOthers": "0",
  "totalCapacityUsed": 4.428248999999999,
  "availableCapacity": 3.071751000000001,
  "availableCapacityPct": 0.4095668000000001,
  "towerLoadingStatus": "Not Overloaded",
  "solarized": "No",
  "solarDeployDate": null,
  "solarLoadDesign": "No",
  "onGrid": null,
  "gridType": "Good Grid",
  "transformerEntity": "Deodar",
  "transformerCapacityKVA": "25 KVA",
  "numRectifiers": 1,
  "rectifier1Manufacturer": "Huawei ETP48400",
  "rectifier1CapacityKW": 12,
  "rectifier1Modules": 4,
  "rectifier2Manufacturer": null,
  "batteryBank1Type": "Huawei Li-ion (100 AH)",
  "batteryBank1Cells": 4,
  "batteryBank1AH": null,
  "batteryBank1Install": "2022-11-01",
  "dg1ModelMake": null,
  "dg1RatingKVA": "30",
  "dg1Status": "Operational",
  "dg1InstallDate": "Greater than 10 years",
  "rms": "Yes",
  "rmsVendor": "Huawei RMS Connected",
  "flmVendor": "Huawei",
  "totalTenants": 1,
  "anchorTenantJazz": 1,
  "thirdPartyTenants": null,
  "guestOMO1": null,
  "guestOMO2": null,
  "guestOMO3": null,
  "hardAccessArea": null,
  "clusterId": 3,
  "isHub": false
 },
 {
  "siteCode": "ALC9648",
  "siteName": "ALC9648__S_MuhallaHaiderabad",
  "lat": 32.2653,
  "lon": 73.808,
  "region": "Central A",
  "zone": 9,
  "city": "Alipur Chatha",
  "tehsil": "WAZIRABAD ",
  "district": "GUJRANWALA",
  "province": "PUNJAB",
  "onAirDate": "2007-03-27",
  "opStatus": "On Air",
  "structureType": "Self-Supported Tower",
  "towerHeight": 37,
  "siteType": "GBT",
  "siteCategory": "Normal",
  "commercialCategory": "Platinum",
  "indoorOutdoor": "Outdoor",
  "macroTxn": "MACRO",
  "vendor": "Huawei",
  "currentTech": "2G+4G",
  "total2G": 3,
  "total4G": 9,
  "mbu": "C4-HFZ-06",
  "mbuLead": "Syed Mansoor Hyder Shah",
  "mbuLeadEmail": "mansoor.hyder@engro.com",
  "mbuLeadContact": "0300-8673770",
  "zonalManager": "Ovais Ali Khan",
  "zonalManagerEmail": "ovais.ali@engro.com",
  "zonalManagerContact": "0306-4000683",
  "roh": "Waqas  Naeem",
  "rohEmail": "waqas.naeem@engro.com",
  "rohContact": "0300-8711033",
  "address": "Khewat No 276, Khatooni No 547, Khasra No 3890/1826 situated at Muhallah Haiderabad, Qadarabad Road, Alipur Chattha",
  "dateOfConstruction": "2016-08-26",
  "leaseExpiry": "2027-02-06",
  "annualRent": 800000,
  "landlordType": "INDIVIDUAL",
  "dualBandAntennas": 3,
  "tribandAntennas": 3,
  "antenna4T6S": 0,
  "mmAntenna": 0,
  "massiveMimoAAU": 0,
  "totalRFAntenna": 6,
  "totalRRUs": 15,
  "totalMWAntenna": 1,
  "fiber": "No",
  "noOfBSDDishes": 0,
  "sizeOfDishes": 0,
  "designCapacity": 7.5,
  "capacityUsedJazz": 4.275753,
  "capacityUsedOthers": 4.513743,
  "totalCapacityUsed": 8.789496,
  "availableCapacity": -1.2894959999999998,
  "availableCapacityPct": -0.17193279999999997,
  "towerLoadingStatus": "Slightly Overloaded",
  "solarized": "No",
  "solarDeployDate": null,
  "solarLoadDesign": "No",
  "onGrid": null,
  "gridType": "Good Grid",
  "transformerEntity": "Deodar",
  "transformerCapacityKVA": "25 KVA",
  "numRectifiers": 1,
  "rectifier1Manufacturer": "Vertiv",
  "rectifier1CapacityKW": null,
  "rectifier1Modules": null,
  "rectifier2Manufacturer": null,
  "batteryBank1Type": "Huawei Li-ion (100 AH)",
  "batteryBank1Cells": 4,
  "batteryBank1AH": null,
  "batteryBank1Install": "2023-11-21",
  "dg1ModelMake": null,
  "dg1RatingKVA": "20",
  "dg1Status": "Operational",
  "dg1InstallDate": "Greater than 10 years",
  "rms": "No",
  "rmsVendor": "No",
  "flmVendor": "Huawei",
  "totalTenants": 2,
  "anchorTenantJazz": 1,
  "thirdPartyTenants": 1,
  "guestOMO1": "Telenor",
  "guestOMO2": null,
  "guestOMO3": null,
  "hardAccessArea": null,
  "clusterId": 3,
  "isHub": false
 },
 {
  "siteCode": "ALI7332",
  "siteName": "ALI7332__H_Chak28_2L",
  "lat": 30.7937,
  "lon": 73.5243,
  "region": "Central A",
  "zone": 2,
  "city": "Alipur",
  "tehsil": "OKARA ",
  "district": "OKARA",
  "province": "PUNJAB",
  "onAirDate": "2009-06-04",
  "opStatus": "On Air",
  "structureType": "Self-Supported Tower",
  "towerHeight": 46,
  "siteType": "GBT",
  "siteCategory": "Normal",
  "commercialCategory": "General",
  "indoorOutdoor": "Outdoor",
  "macroTxn": "MACRO",
  "vendor": "Huawei",
  "currentTech": "2G+4G",
  "total2G": 3,
  "total4G": 9,
  "mbu": "C3-OKA-03",
  "mbuLead": "Manzoor  Hussain",
  "mbuLeadEmail": "manzoor.hussain@engro.com",
  "mbuLeadContact": "0302-8660643",
  "zonalManager": "Usman  Khalid",
  "zonalManagerEmail": "usman.khalid@engro.com",
  "zonalManagerContact": "0302-8480264",
  "roh": "Waqas  Naeem",
  "rohEmail": "waqas.naeem@engro.com",
  "rohContact": "0300-8711033",
  "address": "Khewat No35,Khetoni No216,Khasra No44/25,Chak No28/2-L,Dipalpur Road,Okara",
  "dateOfConstruction": "2009-06-04",
  "leaseExpiry": "2028-02-03",
  "annualRent": 226395.2775,
  "landlordType": "INDIVIDUAL",
  "dualBandAntennas": 3,
  "tribandAntennas": 3,
  "antenna4T6S": 0,
  "mmAntenna": 0,
  "massiveMimoAAU": 0,
  "totalRFAntenna": 6,
  "totalRRUs": 12,
  "totalMWAntenna": 5,
  "fiber": "No",
  "noOfBSDDishes": 0,
  "sizeOfDishes": 0,
  "designCapacity": 12.66,
  "capacityUsedJazz": 6.889803000000001,
  "capacityUsedOthers": "0",
  "totalCapacityUsed": 6.889803000000001,
  "availableCapacity": 5.770197,
  "availableCapacityPct": 0.45578175355450234,
  "towerLoadingStatus": "Not Overloaded",
  "solarized": "No",
  "solarDeployDate": null,
  "solarLoadDesign": "No",
  "onGrid": null,
  "gridType": "Good Grid",
  "transformerEntity": "Deodar",
  "transformerCapacityKVA": "25 KVA",
  "numRectifiers": 1,
  "rectifier1Manufacturer": "Huawei-3KW",
  "rectifier1CapacityKW": null,
  "rectifier1Modules": null,
  "rectifier2Manufacturer": null,
  "batteryBank1Type": "Obsolete",
  "batteryBank1Cells": 4,
  "batteryBank1AH": null,
  "batteryBank1Install": "Greater than 5 years",
  "dg1ModelMake": null,
  "dg1RatingKVA": "9",
  "dg1Status": "Operational",
  "dg1InstallDate": "Greater than 10 years",
  "rms": "Yes",
  "rmsVendor": "Huawei RMS Connected",
  "flmVendor": "HNL",
  "totalTenants": 1,
  "anchorTenantJazz": 1,
  "thirdPartyTenants": null,
  "guestOMO1": null,
  "guestOMO2": null,
  "guestOMO3": null,
  "hardAccessArea": null,
  "clusterId": 4,
  "isHub": true
 },
 {
  "siteCode": "AMG8795",
  "siteName": "AMG8795__S_Ludhaywala",
  "lat": 32.2814,
  "lon": 74.0179,
  "region": "Central A",
  "zone": 9,
  "city": "Ahmed Nagar",
  "tehsil": "WAZIRABAD ",
  "district": "GUJRANWALA",
  "province": "PUNJAB",
  "onAirDate": "2006-11-26",
  "opStatus": "On Air",
  "structureType": "Self-Supported Tower",
  "towerHeight": 46,
  "siteType": "GBT",
  "siteCategory": "Normal",
  "commercialCategory": "Platinum",
  "indoorOutdoor": "Outdoor",
  "macroTxn": "MACRO",
  "vendor": "Huawei",
  "currentTech": "2G+4G",
  "total2G": 4,
  "total4G": 12,
  "mbu": "C4-HFZ-06",
  "mbuLead": "Syed Mansoor Hyder Shah",
  "mbuLeadEmail": "mansoor.hyder@engro.com",
  "mbuLeadContact": "0300-8673770",
  "zonalManager": "Ovais Ali Khan",
  "zonalManagerEmail": "ovais.ali@engro.com",
  "zonalManagerContact": "0306-4000683",
  "roh": "Waqas  Naeem",
  "rohEmail": "waqas.naeem@engro.com",
  "rohContact": "0300-8711033",
  "address": "Khewat No 480, Khetoni No 1017, Khasra No 2946 situated at Ladhaywala Cheema, Tehsil Wazirabad, Distt Gujranwala",
  "dateOfConstruction": "2010-04-21",
  "leaseExpiry": "2034-09-09",
  "annualRent": 577867.5,
  "landlordType": "INDIVIDUAL",
  "dualBandAntennas": 4,
  "tribandAntennas": 4,
  "antenna4T6S": 0,
  "mmAntenna": 0,
  "massiveMimoAAU": 0,
  "totalRFAntenna": 8,
  "totalRRUs": 16,
  "totalMWAntenna": 1,
  "fiber": "No",
  "noOfBSDDishes": 0,
  "sizeOfDishes": 0,
  "designCapacity": 12.66,
  "capacityUsedJazz": 5.9600539999999995,
  "capacityUsedOthers": 2.5776,
  "totalCapacityUsed": 8.537654,
  "availableCapacity": 4.122346,
  "availableCapacityPct": 0.32561974723538706,
  "towerLoadingStatus": "Not Overloaded",
  "solarized": "No",
  "solarDeployDate": null,
  "solarLoadDesign": "No",
  "onGrid": null,
  "gridType": "Bad Grid",
  "transformerEntity": "Deodar",
  "transformerCapacityKVA": "25 KVA",
  "numRectifiers": 1,
  "rectifier1Manufacturer": "Huawei",
  "rectifier1CapacityKW": null,
  "rectifier1Modules": 24,
  "rectifier2Manufacturer": null,
  "batteryBank1Type": "Huawei Li-ion (100 AH)",
  "batteryBank1Cells": 6,
  "batteryBank1AH": null,
  "batteryBank1Install": "2022-04-23",
  "dg1ModelMake": null,
  "dg1RatingKVA": "30",
  "dg1Status": "Operational",
  "dg1InstallDate": "Greater than 10 years",
  "rms": "No",
  "rmsVendor": "No",
  "flmVendor": "Huawei",
  "totalTenants": 2,
  "anchorTenantJazz": 1,
  "thirdPartyTenants": 1,
  "guestOMO1": "CM-PAK",
  "guestOMO2": null,
  "guestOMO3": null,
  "hardAccessArea": null,
  "clusterId": 5,
  "isHub": true
 }
];

window.SMDB_NETWORK = {
 "edges": [
  {
   "from": "AHM8024",
   "to": "AHM8025",
   "type": "access",
   "distanceKm": 6.81
  },
  {
   "from": "AKA7571",
   "to": "AKA7572",
   "type": "access",
   "distanceKm": 4.74
  },
  {
   "from": "ALC3049",
   "to": "ALC3447",
   "type": "access",
   "distanceKm": 0.66
  },
  {
   "from": "ALC8810",
   "to": "ALC3447",
   "type": "access",
   "distanceKm": 0.22
  },
  {
   "from": "ALC9648",
   "to": "ALC3447",
   "type": "access",
   "distanceKm": 0.79
  },
  {
   "from": "AHM8025",
   "to": "ALI7332",
   "type": "backbone",
   "distanceKm": 60.91
  },
  {
   "from": "AHM8025",
   "to": "AKA7572",
   "type": "backbone",
   "distanceKm": 113.59
  },
  {
   "from": "ALI7332",
   "to": "ALC3447",
   "type": "backbone",
   "distanceKm": 166.04
  },
  {
   "from": "ALC3447",
   "to": "AMG8795",
   "type": "backbone",
   "distanceKm": 19.02
  },
  {
   "from": "ALC3447",
   "to": "AKD2954",
   "type": "backbone",
   "distanceKm": 47.1
  }
 ],
 "clusterCount": 6
};
